# Config
    include = "~~/profiles.conf"
    include = "~~/script-opts.conf"
    # log-file = "~~/mpv.log"
    use-filedir-conf = yes

# Window
    idle = yes
    pause = yes
    keep-open = yes
    title-bar = no

# Cache
    cache-on-disk = no
    demuxer-max-bytes = 2048MiB
    demuxer-max-back-bytes = 2048MiB
    gpu-shader-cache = yes
    save-position-on-quit = yes
    watch-later-options = start,vid,aid,sid
    ignore-path-in-watch-later-config = yes

# Input
    input-builtin-bindings = no
    msg-level = "input=error"

# OSD
    osc = no
    osd-on-seek = no
    osd-color = 1/0.75
    osd-border-color = 0/0.75
    osd-border-size = 1
    osd-font = "GenSenRounded2 JP R"
    osd-font-size = 40
    osd-fractions = yes
    # osd-scale-by-window = no

# Video
    hwdec = auto
    profile = high-quality
    video-sync = display-resample
    deinterlace = auto
    deband = no
    image-display-duration=inf

# Audio
    alang = ja,zh-Hans,zh-CN,en
    audio-file-auto = fuzzy
    audio-channels = auto

# Subtitle
    slang = zh-Hans,zh-CN,en,ja
    sub-auto = fuzzy
    sub-file-paths = subs;subtitles
    subs-fallback = yes
    blend-subtitles = no
    sub-font = "GenSenRounded2 JP R"
    sub-font-size = 40
    # sub-scale-with-window = no
    # sub-border-style = background-box
    sub-border-size = 1
    sub-border-color = 0/0.75
    sub-color = 1/0.75
    sub-back-color = 0/0.25
    sub-use-margins = yes
    sub-ass-use-video-data = all
    # sub-ass-override = force
    # sub-ass-scale-with-window = yes
    sub-ass-force-margins = yes
    # stretch-image-subs-to-screen = yes
    # image-subs-video-resolution = yes
    secondary-sub-ass-override = yes

# Screenshot
    screenshot-format = avif
    screenshot-tag-colorspace = yes
    screenshot-high-bit-depth = yes
    screenshot-avif-opts = usage=allintra,crf=23,cpu-used=6
    screenshot-template = "~/Pictures/Screenshots/%F@%wm.%wS.%wT"
