[extension.apng]
    loop = yes
    pause = no

[disable_position]
    profile-desc = disable position saving
    profile-cond = p["current-tracks/video/albumart"] or p["current-tracks/video/image"] or p.duration<=300 or p.percent_pos<=10 or p.percent_pos>=90
    profile-restore = copy
    save-position-on-quit = no

[deband]
    profile-desc = deband low bitrate video
    profile-cond = not (p["current-tracks/video/albumart"] or p["current-tracks/video/image"]) and (p.file_size/p.duration<=250000)
    profile-restore = copy
    deband = yes
    deband-iterations = 2
    deband-threshold = 35
    deband-range = 20
    deband-grain = 5

[deband_off]
    profile-desc = no deband
    deband = no

[deband_standard]
    profile-desc = standard deband
    deband = yes
    deband-iterations = 2
    deband-threshold = 35
    deband-range = 20
    deband-grain = 5

[deband_stronger]
    profile-desc = stronger deband
    deband = yes
    deband-iterations = 3
    deband-threshold = 45
    deband-range = 25
    deband-grain = 15

[deband_strongest]
    profile-desc = strongest deband
    deband = yes
    deband-iterations = 4
    deband-threshold = 60
    deband-range = 30
    deband-grain = 30
