[extension.apng]
    loop = yes
    pause = no

[disable_position]
    profile-desc = disable position saving
    profile-cond = p["current-tracks/video/albumart"] or p["current-tracks/video/image"] or p.duration<=300 or p.percent_pos<=10 or p.percent_pos>=90
    profile-restore = copy
    save-position-on-quit = no

[deband]
    profile-desc = deband low bitrate video
    profile-cond = not (p["current-tracks/video/albumart"] or p["current-tracks/video/image"]) and (p.file_size/p.duration<=250000)
    profile-restore = copy
    deband = yes
